# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Kocli < Formula
  desc "Internal Kolors CLI"
  homepage "https://github.com/10xLabs/kocli"
  version "1.36.0-pre.3"
  license "MIT"

  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/10xLabs/kocli/releases/download/v1.36.0-pre.3/kocli_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "301f6729eae57b1206741aaf50bc16aa134da732d25fd2af0f9ecb6f3d99ca88"

      def install
        bin.install "ko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/10xLabs/kocli/releases/download/v1.36.0-pre.3/kocli_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "701b81e228a6a590face047f3cdb099f739d3843ea7fee0b7ff5c2c1241a3d48"

      def install
        bin.install "ko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/10xLabs/kocli/releases/download/v1.36.0-pre.3/kocli_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "511762d738614da060ea4631d148dcec7d7d3d901b0e0b38e0ba8533ab2d3b14"
      def install
        bin.install "ko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/10xLabs/kocli/releases/download/v1.36.0-pre.3/kocli_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "83ac27c14b295a6befcc258c53f864a0c8f734511c7900c195a1632afe9fedd4"
      def install
        bin.install "ko"
      end
    end
  end

  head "https://github.com/10xLabs/kocli.git"

  def caveats
    <<~EOS
      To start using kocli use "ko"
        ko --help
        ko --version
    EOS
  end

  test do
    ko --help
  end
end
