# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Kocli < Formula
  desc "Internal Kolors CLI"
  homepage "https://github.com/10xLabs/kocli"
  version "1.29.0"
  license "MIT"

  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    on_intel do
      url "https://github.com/10xLabs/kocli/releases/download/v1.29.0/kocli_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "29654f095a16c01929770ea5ee2c16ab0998f75a312b75d82c93e5435f13aaf1"

      def install
        bin.install "ko"
      end
    end
    on_arm do
      url "https://github.com/10xLabs/kocli/releases/download/v1.29.0/kocli_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c2466e9362f031d90bd987693d88ad7e38105821c69bf3f34a9dc77a5550db30"

      def install
        bin.install "ko"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/10xLabs/kocli/releases/download/v1.29.0/kocli_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "aea7e7ad40ee06e24242877a866b26716653a929edd042239bc416bd126560f3"

        def install
          bin.install "ko"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/10xLabs/kocli/releases/download/v1.29.0/kocli_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "3ac766f8af0cdb693fa4a51b23ecee39df748549b5242e149fc57ac1d0df5f6e"

        def install
          bin.install "ko"
        end
      end
    end
  end

  head "https://github.com/10xLabs/kocli.git"

  def caveats
    <<~EOS
      To start using kocli use "ko"
        ko --help
        ko --version
    EOS
  end

  test do
    ko --help
  end
end
