# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Kocli < Formula
  desc "Internal Kolors CLI"
  homepage "https://github.com/10xLabs/kocli"
  version "1.35.1"
  license "MIT"

  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    on_intel do
      url "https://github.com/10xLabs/kocli/releases/download/v1.35.1/kocli_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "38b63733a1075d3a90a7fffbdab0126f0857d120e225af27e7d546d6861d3dea"

      def install
        bin.install "ko"
      end
    end
    on_arm do
      url "https://github.com/10xLabs/kocli/releases/download/v1.35.1/kocli_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f4204b92e4f233c539b4d486eb056c08474509da90ffaf27e4d89cdea571ed1b"

      def install
        bin.install "ko"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/10xLabs/kocli/releases/download/v1.35.1/kocli_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "202784d9591c818570e11d191277e3b665663af97924849243f5e2c5fa3caaf2"

        def install
          bin.install "ko"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/10xLabs/kocli/releases/download/v1.35.1/kocli_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "7c250ddf2d13792e3a21794a209686512a7432878200b16ce8f6b69966745795"

        def install
          bin.install "ko"
        end
      end
    end
  end

  head "https://github.com/10xLabs/kocli.git"

  def caveats
    <<~EOS
      To start using kocli use "ko"
        ko --help
        ko --version
    EOS
  end

  test do
    ko --help
  end
end
